#===================================================
#                 Namespaces
#===================================================
apiVersion: v1
kind: Namespace
metadata:
  name: logbeacon
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
#===================================================
#                 Service Accounts
#===================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logbeacon
  namespace: logbeacon
  annotations:
    argocd.argoproj.io/sync-wave: "1"