apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: workload-cluster
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: workload-cluster
    creationPolicy: Owner

    template:
      type: Opaque

      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster

      data:
        name: workload-cluster
        server: "{{ .SERVER }}"
        config: |
          {
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .CA_DATA }}"
            }
          }

  dataFrom:
    - extract:
        key: workload-eks-cred