apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "15"

spec:
  project: default
  source:
    repoURL: https://github.com/iamridoydey/logbeacon-aws-k8s.git
    targetRevision: HEAD
    path: infra-resources/external-secrets/workload
  
  destination:
    name: workload-cluster

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true