apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: workload-cluster
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: workload-cluster-secret
    creationPolicy: Orphan
    deletionPolicy: Retain

    template:
      type: Opaque

      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster

      data:
        name: workload-cluster
        server: "{{ .SERVER }}"
        config: |
          {
            "awsAuthConfig": {
              "clusterName": "{{ .WORKLOAD_CLUSTER_NAME }}",
              "roleARN": "{{ .WORKLOAD_CLUSTER_ROLE_ARN }}"
            },
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .CA_DATA }}"
            }
          }

  dataFrom:
    - extract:
        key: workload-eks-cred