apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logbeacon

resources:
  - ../../base

patches:
  - path: backend-configmap.yaml
  - path: frontend-configmap.yaml
  - path: backend-rollout.yaml
  - path: frontend-rollout.yaml
  - path: certificate.yaml
  - path: gateway.yaml
  - path: httproute.yaml