crds:
  install: true
  keep: true

  annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true
      
serviceAccount:
  create: true
  name: argocd-image-updater

config:
  log.level: info

  registries:
    - name: ECR
      api_url: https://869719105525.dkr.ecr.us-east-1.amazonaws.com
      prefix: 869719105525.dkr.ecr.us-east-1.amazonaws.com
      credentials: ext:/scripts/auth-ecr.sh
      credsexpire: 10h

authScripts:
  enabled: true

  scripts:
    auth-ecr.sh: |
      #!/bin/sh
      aws ecr --region us-east-1 get-authorization-token \
        --output text \
        --query 'authorizationData[].authorizationToken' | base64 -d