architecture: standalone

global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.5.0-debian-12-r20

auth:
  existingSecret: logbeacon-app-secret

  secretKeys:
    adminPasswordKey: POSTGRES_PASSWORD
    userPasswordKey: POSTGRES_PASSWORD

  username: logbeacon
  database: logbeacon_db

primary:
  persistence:
    enabled: true
    storageClass: ebs-gp3
    size: 8Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "500m"
      memory: 512Mi

service:
  type: ClusterIP