community:
  enabled: true

monitoringPasscodeSecretName: sonarqube-monitoring-passcode
monitoringPasscodeSecretKey: monitoringPasscode

serviceAccount:
  create: true
  name: sonarqube
  automountToken: true

persistence:
  enabled: true
  storageClass: ebs-gp3
  size: 10Gi

resources:
  requests:
    cpu: 256m
    memory: 1Gi

  limits:
    cpu: "512m"
    memory: 2Gi

service:
  type: ClusterIP