apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater

metadata:
  name: logbeacon-image-updater
  namespace: argocd

spec:
  writeBackConfig:
    method: "git:secret:argocd/github-secret"

    gitConfig:
      repository: "https://github.com/iamridoydey/logbeacon-aws-k8s.git"
      branch: "main"
      writeBackTarget: "kustomization:logbeacon"
      # Don't support direct push. Need a pull request before merge
      pullRequest:
        github: {}

  applicationRefs:
    - namePattern: "workload-logbeacon-apps"

      images:
        - alias: frontend
          imageName: "869719105525.dkr.ecr.us-east-1.amazonaws.com/logbeacon/frontend"

          commonUpdateSettings:
            updateStrategy: newest-build

          manifestTargets:
            kustomize:
              name: "logbeacon/frontend"

        - alias: backend
          imageName: "869719105525.dkr.ecr.us-east-1.amazonaws.com/logbeacon/backend"

          commonUpdateSettings:
            updateStrategy: newest-build

          manifestTargets:
            kustomize:
              name: "logbeacon/backend"
