apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-cluster-secret-store
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "10"

spec:
  project: default
  source:
    repoURL: https://github.com/iamridoydey/logbeacon-aws-k8s.git
    targetRevision: HEAD
    path: infra-resources/cluster-secret-stores

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
