apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: management-image-updater-resources
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "45"

spec:
  project: default

  source:
    repoURL: https://github.com/iamridoydey/logbeacon-aws-k8s.git
    targetRevision: main
    path: infra-resources/image-updater

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true