apiVersion: argoproj.io/v1alpha1
kind: Rollout

metadata:
  name: logbeacon-backend

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: backend
          image: logbeacon/backend:dev