apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logbeacon-tls
  namespace: logbeacon

spec:
  secretName: logbeacon-tls

  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer

  dnsNames:
    - dev.aws-logbeacon.iamridoydey.me
    - api.dev.aws-logbeacon.iamridoydey.me