apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: logbeacon-app-secret
  namespace: logbeacon

  annotations:
    argocd.argoproj.io/sync-wave: "3"

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: logbeacon-app-secret
    creationPolicy: Owner

  data:
    # ---------------------------------------------------------
    # Application
    # ---------------------------------------------------------

    - secretKey: SECRET_KEY
      remoteRef:
        key: logbeacon/app
        property: SECRET_KEY

    - secretKey: GROQ_API_KEY
      remoteRef:
        key: logbeacon/app
        property: GROQ_API_KEY

    - secretKey: SESSION_SECRET
      remoteRef:
        key: logbeacon/app
        property: SESSION_SECRET

    # ---------------------------------------------------------
    # PostgreSQL
    # ---------------------------------------------------------

    - secretKey: POSTGRES_USER
      remoteRef:
        key: logbeacon/database
        property: POSTGRES_USER

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: logbeacon/database
        property: POSTGRES_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: logbeacon/database
        property: POSTGRES_DB

    # ---------------------------------------------------------
    # SMTP
    # ---------------------------------------------------------

    - secretKey: SMTP_USER
      remoteRef:
        key: logbeacon/smtp
        property: SMTP_USER

    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: logbeacon/smtp
        property: SMTP_PASSWORD

    - secretKey: FROM_EMAIL
      remoteRef:
        key: logbeacon/smtp
        property: FROM_EMAIL