apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: workload-argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"

spec:
  project: default

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: "2.43.0"

    helm:
      valuesObject:
        controller:
          trafficRouterPlugins:
            - name: argoproj-labs/gatewayAPI
              location: https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.16.0/gatewayapi-plugin-linux-amd64

        providerRBAC:
          enabled: true
          providers:
            gatewayAPI: true

  destination:
    name: workload-cluster
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true