apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: workload-external-dns
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "40"

spec:
  project: default

  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.21.1

      helm:
        valueFiles:
          - $values/infra/workload-external-dns-values.yaml
    - repoURL: https://github.com/iamridoydey/logbeacon-aws-k8s.git
      targetRevision: main
      ref: values

  destination:
    name: workload-cluster
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
