apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: workload-external-secrets
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "5"

spec:
  project: default

  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.8.0

      helm:
        valueFiles:
          - $values/infra/external-secrets-values.yaml

    - repoURL: https://github.com/iamridoydey/logbeacon-aws-k8s.git
      targetRevision: main
      ref: values

  destination:
    name: workload-cluster
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Reduced the annotation size
