apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: sonarqube-monitoring-passcode
  namespace: sonarqube

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: sonarqube-monitoring-passcode
    creationPolicy: Owner

  data:
    - secretKey: monitoringPasscode
      remoteRef:
        key: logbeacon/sonarqube-passcode
        property: MONITORING_PASSCODE