apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Workload cluster Helm applications
  - charts/cert-manager.yaml
  - charts/external-dns.yaml
  - charts/external-secrets.yaml
  - charts/traefik.yaml
  - charts/postgresql.yaml
  - charts/redis.yaml
  - charts/sonarqube.yaml
  - charts/argo-rollouts.yaml
  # Workload cluster raw-resource applications
  # - resources/ns-sa.yaml # Don't it now
  - resources/cluster-secret-store.yaml
  - resources/external-secrets.yaml
  - resources/storage-class.yaml
  - resources/gateway-api.yaml
  # - apps/workload-apps-dev.yaml
  # - apps/workload-apps-qa.yaml
  - apps/workload-apps-prod.yaml # Only run prod to reduce the cost