apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Wave -1 - Namespaces and ServiceAccounts
  - resources/ns-sa.yaml

  # Wave 0 - StorageClass
  - resources/storage-class.yaml

  # Wave 5 - External Secrets Operator
  - charts/external-secrets.yaml

  # Wave 10 - ClusterSecretStore
  - resources/cluster-secret-store.yaml

  # Wave 15 - ExternalSecrets
  # Creates application, Cloudflare, SonarQube secrets, etc.
  - resources/external-secrets.yaml

  # Wave 20 - cert-manager controller + CRDs
  - charts/cert-manager.yaml

  # Wave 25 - cert-manager resources
  - resources/certificate.yaml

  # Wave 30 - Traefik
  - charts/traefik.yaml

  # Wave 35 - ExternalDNS
  - charts/external-dns.yaml

  # Wave 40 - Argo Rollouts controller + CRDs
  - charts/argo-rollouts.yaml

  # Wave 45 - Redis
  - charts/redis.yaml

  # Wave 50 - PostgreSQL
  - charts/postgresql.yaml

  # Wave 55 - SonarQube
  - charts/sonarqube.yaml

  # Wave 60 - LogBeacon application
  - apps/workload-apps.yaml