apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: workload-logbeacon-apps
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "60"

spec:
  project: default

  source:
    repoURL: https://github.com/iamridoydey/logbeacon-aws-k8s.git
    targetRevision: main
    path: apps/workload

  destination:
    name: workload-cluster
    namespace: logbeacon

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true