apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
    # Apart from these two file we have everything by default.
  - path: backend-rollout.yaml
  - path: frontend-rollout.yaml
