apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Management cluster Helm applications
  - charts/cert-manager.yaml
  - charts/external-dns.yaml
  - charts/external-secrets.yaml
  - charts/traefik.yaml
  # Management cluster raw-resource applications
  - resources/namespaces.yaml
  - resources/cluster-secret-store.yaml
  - resources/secrets.yaml
  - resources/apps.yaml
  # Root Application for the workload cluster
  - resources/workload-root.yaml