apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-tls
  namespace: argocd

  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  secretName: argo-tls

  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer

  dnsNames:
    - "*.aws-logbeacon.iamridoydey.me"